### ISSUE TITLE
Error messages with Mopidy 2.1.0 / Mopidy-Tidal: 0.2.2 / tidalapi4mopidy 0.1.3

### ISSUE THREAD

**Issue by mhacke** [mones88/mopidy-tidal#12]
I installed mopidy using apt-get and mopidy-tidal using pip.

Search and play functionality works with Tidal, but I get the following errors on startup, and at regular intervals.

The output of `mopidy`:

> INFO     Starting Mopidy 2.1.0
> INFO     Loading config from builtin defaults
> INFO     Loading config from /var/lib/mopidy/.config/mopidy/mopidy.conf
> INFO     Loading config from command line options
> INFO     Creating dir /var/lib/mopidy/.cache/mopidy
> INFO     Creating dir /var/lib/mopidy/.local/share/mopidy
> INFO     Enabled extensions: iris, http, stream, local-sqlite, softwaremixer, local-images, tidal, local
> INFO     Disabled extensions: spotify, mpd, m3u, file
> INFO     Starting Mopidy mixer: SoftwareMixer
> INFO     Starting Mopidy audio
> INFO     Starting Mopidy backends: StreamBackend, LocalBackend, TidalBackend
> INFO     Creating dir /var/lib/mopidy/.local/share/mopidy/local-sqlite
> INFO     Creating SQLite database schema v6
> INFO     Audio output set to "autoaudiosink"
> INFO     Loaded 0 local tracks using sqlite
> INFO     Connecting to TIDAL.. Quality = LOSSLESS
> INFO     TIDAL Login OK
> INFO     Starting Mopidy core
> **ERROR    TidalBackend backend caused an exception.**
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
>     yield
>   File "/usr/lib/python2.7/dist-packages/mopidy/core/playlists.py", line 66, in as_list
>     playlists = future.get()
>   File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
>     compat.reraise(*self._data['exc_info'])
>   File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
>     exec('raise tp, value, tb')
>   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
>     response = self._handle_receive(message)
>   File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
>     return callee(*message['args'], **message['kwargs'])
>   File "/usr/lib/python2.7/dist-packages/mopidy_tidal/playlists.py", line 22, in as_list
>     self.refresh()
>   File "/usr/lib/python2.7/dist-packages/mopidy_tidal/playlists.py", line 62, in refresh
>     pl_tracks = session.get_playlist_tracks(pl.id)
>   File "/usr/lib/python2.7/dist-packages/tidalapi4mopidy/__init__.py", line 119, in get_playlist_tracks
>     return self._map_request('playlists/%s/tracks' % playlist_id, ret='tracks')
>   File "/usr/lib/python2.7/dist-packages/tidalapi4mopidy/__init__.py", line 198, in _map_request
>     return list(map(parse, items))
>   File "/usr/lib/python2.7/dist-packages/tidalapi4mopidy/__init__.py", line 265, in _parse_track
>     album = _parse_album(json_obj['album'], artist)
>   File "/usr/lib/python2.7/dist-packages/tidalapi4mopidy/__init__.py", line 235, in _parse_album
>     kwargs['release_date'] = datetime.datetime(*map(int, json_obj['releaseDate'].split('-')))
> AttributeError: 'NoneType' object has no attribute 'split'
> INFO     Starting Mopidy frontends: HttpFrontend, IrisFrontend
> INFO     HTTP server running at [::ffff:0.0.0.0]:6680
> INFO     Starting GLib mainloop
> INFO     Starting Iris 3.14.2
> INFO     Creating dir /var/lib/mopidy/.local/share/mopidy/local-images
> **ERROR    TidalBackend backend caused an exception.**
(The error repeats)

The output of `mopidy deps`:

> Executable: /usr/bin/mopidy
> Platform: Linux-4.15.6-300.fc27.x86_64-x86_64-with-debian-9.3
> Python: CPython 2.7.13 from /usr/lib/python2.7
> Mopidy: 2.1.0 from /usr/lib/python2.7/dist-packages
> Mopidy-Iris: 3.14.2 from /usr/lib/python2.7/dist-packages
>   pylast>=1.6.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>     six: 1.11.0 from /usr/lib/python2.7/dist-packages
>   requests>=2.0.0: 2.18.4 from /usr/lib/python2.7/dist-packages
>     urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/dist-packages
>     idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/dist-packages
>     chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/dist-packages
>     certifi>=2017.4.17: 2018.1.18 from /usr/lib/python2.7/dist-packages
>   Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>   setuptools>=3.3: 38.5.2 from /usr/lib/python2.7/dist-packages
>   Mopidy-Local-Images>=1.0: 1.0.0 from /usr/lib/python2.7/dist-packages
>     Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
>     setuptools: 38.5.2 from /usr/lib/python2.7/dist-packages
>     Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
>     uritools>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>       ipaddress; python_version == "2.7": 1.0.19 from /usr/lib/python2.7/dist-packages
>   ConfigObj>=5.0.6: 5.0.6 from /usr/lib/python2.7/dist-packages
>     six: 1.11.0 from /usr/lib/python2.7/dist-packages
>   raven>=6.1.0: 6.6.0 from /usr/lib/python2.7/dist-packages
>     contextlib2; python_version < "3.2": 0.5.5 from /usr/lib/python2.7/dist-packages
> Mopidy-Local-Images: 1.0.0 from /usr/lib/python2.7/dist-packages
>   Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
>   setuptools: 38.5.2 from /usr/lib/python2.7/dist-packages
>   Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
>   uritools>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>     ipaddress; python_version == "2.7": 1.0.19 from /usr/lib/python2.7/dist-packages
> Mopidy-Tidal: 0.2.2 from /usr/lib/python2.7/dist-packages
>   Mopidy>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>   setuptools: 38.5.2 from /usr/lib/python2.7/dist-packages
>   requests>=2.0.0: 2.18.4 from /usr/lib/python2.7/dist-packages
>     urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/dist-packages
>     idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/dist-packages
>     chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/dist-packages
>     certifi>=2017.4.17: 2018.1.18 from /usr/lib/python2.7/dist-packages
>   Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
>   tidalapi4mopidy>=0.1.2: 0.1.3 from /usr/lib/python2.7/dist-packages
>     requests: 2.18.4 from /usr/lib/python2.7/dist-packages
>       urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/dist-packages
>       idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/dist-packages
>       chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/dist-packages
>       certifi>=2017.4.17: 2018.1.18 from /usr/lib/python2.7/dist-packages
>     pytest: 3.4.2 from /usr/lib/python2.7/dist-packages
>       attrs>=17.2.0: 17.4.0 from /usr/lib/python2.7/dist-packages
>       pluggy<0.7,>=0.5: 0.6.0 from /usr/lib/python2.7/dist-packages
>       funcsigs; python_version < "3.0": 1.0.2 from /usr/lib/python2.7/dist-packages
>       six>=1.10.0: 1.11.0 from /usr/lib/python2.7/dist-packages
>       setuptools: 38.5.2 from /usr/lib/python2.7/dist-packages
>       py>=1.5.0: 1.5.2 from /usr/lib/python2.7/dist-packages
> Mopidy-Local-SQLite: 1.0.0 from /usr/lib/python2.7/dist-packages
>   Mopidy>=1.1: 2.1.0 from /usr/lib/python2.7/dist-packages
>   setuptools: 38.5.2 from /usr/lib/python2.7/dist-packages
>   Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
>   uritools>=1.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>     ipaddress; python_version == "2.7": 1.0.19 from /usr/lib/python2.7/dist-packages
> Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
>   Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/dist-packages
>   Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
>   pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
>     cffi>=1.0.0: 1.9.1 from /usr/lib/python2.7/dist-packages
>   requests>=2.0: 2.18.4 from /usr/lib/python2.7/dist-packages
>     urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/dist-packages
>     idna<2.7,>=2.5: 2.6 from /usr/lib/python2.7/dist-packages
>     chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/dist-packages
>     certifi>=2017.4.17: 2018.1.18 from /usr/lib/python2.7/dist-packages
> GStreamer: 1.10.4.0 from /usr/lib/python2.7/dist-packages/gi
>   Detailed information: 
>     Python wrapper: python-gi 3.22.0
>     Relevant elements:
>       Found:
>         uridecodebin
>         souphttpsrc
>         appsrc
>         alsasink
>         osssink
>         oss4sink
>         pulsesink
>         id3demux
>         id3v2mux
>         lamemp3enc
>         mad
>         mpegaudioparse
>         mpg123audiodec
>         vorbisdec
>         vorbisenc
>         vorbisparse
>         oggdemux
>         oggmux
>         oggparse
>         flacdec
>         flacparse
>         shout2send
>       Not found:
>         flump3dec

Please advise!

**Comment by dhruvmittal** [comment]
I also had this issue-- I solved it by adding an additional except statement to handle the case when the releaseDate field was present but blank. I just did it and submitted the patch, but I don't know if the original developer is active. 

My solution can be found here: https://github.com/dhruvmittal/python-tidal/tree/split_exception_handling

**Comment by mua-dib** [comment]
Hey gents, apologies for not knowing what I'm talking about, I've installed tidal4mopidy and mopidy-tidal, but I still can't get mopidy to do anything without getting the  **ERROR TidalBackend backend caused an exception** issue outlined above.

What do I need to do? roll back to the step in the mopidy-tidal install where I just have the git repo downloaded, and then paste in the specific filed from tidal4mopidy?

Full paste
`ERROR    TidalBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python2.7/site-packages/mopidy/core/playlists.py", line 18, in _backend_error_handling
    yield
  File "/home/osboxes/.local/lib/python2.7/site-packages/mopidy/core/playlists.py", line 66, in as_list
    playlists = future.get()
  File "/home/osboxes/.local/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/home/osboxes/.local/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/home/osboxes/.local/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/home/osboxes/.local/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/home/osboxes/.local/lib/python2.7/site-packages/mopidy_tidal/playlists.py", line 22, in as_list
    self.refresh()
  File "/home/osboxes/.local/lib/python2.7/site-packages/mopidy_tidal/playlists.py", line 62, in refresh
    pl_tracks = session.get_playlist_tracks(pl.id)
  File "/home/osboxes/.local/lib/python2.7/site-packages/tidalapi4mopidy/__init__.py", line 119, in get_playlist_tracks
    return self._map_request('playlists/%s/tracks' % playlist_id, ret='tracks')
  File "/home/osboxes/.local/lib/python2.7/site-packages/tidalapi4mopidy/__init__.py", line 198, in _map_request
    return list(map(parse, items))
  File "/home/osboxes/.local/lib/python2.7/site-packages/tidalapi4mopidy/__init__.py", line 265, in _parse_track
    album = _parse_album(json_obj['album'], artist)
  File "/home/osboxes/.local/lib/python2.7/site-packages/tidalapi4mopidy/__init__.py", line 235, in _parse_album
    kwargs['release_date'] = datetime.datetime(*map(int, json_obj['releaseDate'].split('-')))
AttributeError: 'NoneType' object has no attribute 'split'
`

**Comment by dhruvmittal** [comment]
Hi @mua-dib, your error looks like the same one I had here! My patch to fix it was accepted, but I don't know how long before a new package is uploaded further upstream. If you're willing, you can manually install the package by cloning mones88/python-tidal. You can also do as I did and add the two lines to your existing python-tidal installation (https://github.com/mones88/python-tidal/commit/2481c24b1615c215614a33311c02078eaf667b1e). 

Hope that helps!
