### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by o1gres** [mones88/mopidy-tidal#13]
Is it possible login using the facebook account?

Thanks

**Comment by mones88** [comment]
Not directly, a tidal username/password is required.

I found this on the web, give it a try
1 - Go to https://listen.tidalhifi.com/ 
2 - Click Log In
3 - Click Forgot your password?
4 - Enter the email address associated with your Facebook or Twitter account and click Request new password.

Let me know if it works...
