### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by shawaj** [mones88/mopidy-tidal#5]
Do you need help maintaining this or adding features?

**Comment by mones88** [comment]
Definitly yes as I don't have a subscription anymore.
If you are willing to collaborate I can add you as 'collaborator' giving you push permission.

**Comment by shawaj** [comment]
Ok great! Sounds perfect. We can also give you access to our Tidal account
if you need to play with one.

Also - send me an email to shawaj at gmail dot com

Thanks

**Comment by shawaj** [comment]
@mones88 did you see my latest comment?

**Comment by mones88** [comment]
Hi Aaron,
yes, I did!
I've added you as collaborator more than a week ago. GitHub says it's
waiting for your response.
For convenience here's the link to accept the request: https://github.com/
mones88/mopidy-tidal/invitations

I also sent you an email to your personal address, maybe it ended up in the
spam folder.




2016-09-15 0:10 GMT+02:00 Aaron Shaw <notifications@github.com>:

**Comment by shawaj** [comment]
Just found them in my spam! Thanks
