### ISSUE TITLE
Lossless streaming not working since yesterday

### ISSUE THREAD

**Issue by floribauer** [mones88/mopidy-tidal#6]
The option HIGH in mopidy.conf is working for me.
I found a link for this issue in kodi forum: http://forum.kodi.tv/showthread.php?tid=200555&pid=2415125#pid2415125
But the described solution is not working for me. Can't get LOSSLESS working anymore.

**Comment by antonjah** [comment]
Same for me, log here:
http://www.hastebin.com/osuqizafix.log

**Comment by mones88** [comment]
Most of the FLAC streams are now crypted :(
I don't know if there's anything we can do for now.

**Comment by mones88** [comment]
Maybe I found a workaround, please give a try updating **tidalapi4mopidy**  to **0.1.3**.
Let me know....
